language: node_js
node_js:
- 10.16.3
if: branch = master
before_install:
- openssl aes-256-cbc -K $encrypted_1d9f41e8d761_key -iv $encrypted_1d9f41e8d761_iv
  -in secret.json.enc -out secret.json -d
deploy:
  provider: heroku
  app: stalker-bot-discord
  on: master
  api_key:
    secure: QfDI7TxNXt/P8fT7mM/ZP0RQQLajikGr0rJsd3KH8dp95NDICTRL+W28wekD3tw1zfg4Kvrif8d9uTPByfSLh5P7zbJ6AUEzuSCtDregTcCtpOe8Hrgk/FKP78SNNvr9KlccAQzpx7WVMgX1qa7k0ADpaqpJkdg9Q42IPrWXPtEF/66WlAmn6+42LwgHsWXjVovJkO1/cORdaNGQQpHYmx1Jtx6wPAmTMgILuH1sCG5XtiGUon0HDjMuels1EwWPap5F9mcOCm3HcH68EoJnUb7bIWDp+wVRH32DOnikxnOnvsKCF5UhfhLEYP+SCf1HOfyjE+yfwnn75NDf+tN74MPYOOdfhYx7/djm7ZNxbDikq1sXzh9/LH8xqQEV9vJ04GMDKPay4aGyJjuFkP7BeirLDoUqrHvAAkY0TF5uyCOjjmyPxB6hFsQB7p4v1IJkdkO6wOZFE3B6vDpa+wqJ18+wX3jOFWJJBnSvqlXjQTWzVV7Pv29j/bUtkYeH8QLbGKywaGK6q4Yp2LrG6nyLBRtONPPtYI1aVXCGuQqEvAkN/8nLHxKG9r/LCc+0axYYx7barhgZGuRPE7c8Ayb+FLAve04O1GpJrDau/iv8SUriAOeCK5CVy/frGPN463Qhwn89wvh6Frl24VH/nZjiyEILwzah5QFrz96+Owxxt6Y=
